### ISSUE TITLE
not removing sse from poll whe client close the connection

### ISSUE THREAD

**Issue by panManfredini** [yklykl530/koa-sse#5]
Hi,

I'm no expert but looks like when is the client to close the connection (for example pressing the refresh button) then the socket is not removed from the socket list.

I get this error when pinging:
```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
```

I looked into the code and I modified line 44 of lib/index.js 
```js
sse.on('finish', function(){
            ssePool.splice(ssePool.indexOf(sse), 1);
```

with:
```js
sse.on('close', function(){
            ssePool.splice(ssePool.indexOf(sse), 1);
```
and now it is working, but I'm not sure if its the right way to do it.

**Comment by yklykl530** [comment]
Sorry, just replying to you. @panManfredini 
You are right, thanks, I will fix it as soon as possible.

In addition, I also found an API design problem, should not use the `end` method as the interface closed on the server side, `end` is used to let the stream library notify  that the stream has been closed the callback function, I added the `sendEnd` method to Close SSE
Thank you for your use.
