### ISSUE TITLE
[Feature request] Option to disable the ping output

### ISSUE THREAD

**Issue by CedX** [yklykl530/koa-sse#6]
It would be cool if there was an option to disable the output of the ping.

The output is not very useful for my needs, and it uses `console.log` which is a synchronous call on POSIX systems (see https://nodejs.org/api/process.html#process_a_note_on_process_i_o).

**Comment by yornaath** [comment]
Could you please integrate this and push a new version? 🙏

**Comment by CedX** [comment]
@yklykl530 has only one contribution on GitHub during the past year. I think we can close this issue as I doubt that it will be fixed soon. See the PR #6 for a follow up.
